/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GkNjwEC
 */
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { ArrowLeftRight, CircleDollarSign, Home, User2 } from "lucide-react"

export function MenuLayout() {
  return (
    <div className="py-2 border-b fixed w-full mt-28">
      <aside className="sticky h-screen w-56 bg-gray-100 text-gray-800 p-4">
        <div className="flex items-center mb-4 space-x-1">
          <img src="https://i.postimg.cc/66kPCQ8J/gl.png" alt="" 
          className="w-10 h-10 rounded-full"
          />
          <h1 className="text-lg font-medium">Acme</h1>
        </div>
        <nav className="space-y-2">
          <button className="w-full flex items-center space-x-2 hover:bg-gray-200 active:bg-gray-300 py-2 px-2 rounded-lg text-gray-500">
            <Home />
            <span className="text-sm font-medium">Home</span>
          </button>
          <button className="w-full flex items-center space-x-2 bg-gray-200 active:bg-gray-300 py-2 px-2 rounded-lg text-gray-800">
            <ArrowLeftRight />
            <span className="text-sm font-medium">Transactions</span>
          </button>
          <button className="w-full flex items-center space-x-2 hover:bg-gray-200 active:bg-gray-300 py-2 px-2 rounded-lg text-gray-500">
            <User2 />
            <span className="text-sm font-medium">Accounts</span>
          </button>
          <button className="w-full flex items-center space-x-2 hover:bg-gray-200 active:bg-gray-300 py-2 px-2 rounded-lg text-gray-500">
          <CircleDollarSign />
            <span className="text-sm font-medium">Tax</span>
          </button>
        </nav>
      </aside>
    </div>
  )
}
